#!/usr/bin/env bash
# Assemble self-contained, IDE-droppable plugin folders under dist/<engine>.
# POSIX mirror of build.ps1 — see that file for the full layout rationale.
#
# Usage:  sh scripts/build.sh

set -eu

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SHARED="$ROOT/shared"
DIST="$ROOT/dist"
ENGINES="claude codex"

# ---- assemble ----------------------------------------------------------------
for engine in $ENGINES; do
    src="$ROOT/engines/$engine"
    out="$DIST/$engine"

    rm -rf "$out"
    mkdir -p "$out"

    # engine-specific files (the /. form copies dot-prefixed entries too)
    cp -R "$src/." "$out/"

    # shared, engine-agnostic payload
    for s in skills hooks templates; do
        cp -R "$SHARED/$s" "$out/"
    done

    echo "built dist/$engine"
done

# ---- per-engine drop README --------------------------------------------------
cat > "$DIST/claude/README.md" <<'EOF'
# kensa-qa — Claude Code engine (built artifact)

This folder is generated by `scripts/build.sh` — do not edit by hand. Edit the
sources under `shared/` and `engines/claude/`, then rebuild.

A complete, self-contained Claude Code plugin: `.claude-plugin/plugin.json` wires
the Stop hooks and the bundled sequential-thinking MCP. Drop it into the project
as a project-scoped plugin (e.g. `<project>/.claude/plugins/kensa-qa/`) and enable
it, then run `/setup`.
EOF

cat > "$DIST/codex/README.md" <<'EOF'
# kensa-qa — Codex engine (built artifact)

This folder is generated by `scripts/build.sh` — do not edit by hand. Edit the
sources under `shared/` and `engines/codex/`, then rebuild.

Copy the contents into the project root — the layout already mirrors where Codex
expects each piece: `.codex/agents/*.toml` (project-scoped subagents),
`.codex/prompts/*.md`, `AGENTS.md`, `skills/`, `hooks/`, `templates/`, and
`.codex-plugin/plugin.json` for `codex plugin` install. Run `/kensa-setup`.
EOF

# ---- validation --------------------------------------------------------------
errors=0
shared_skills="$(find "$SHARED/skills" -name SKILL.md | wc -l | tr -d ' ')"

for engine in $ENGINES; do
    out="$DIST/$engine"

    n="$(find "$out/skills" -name SKILL.md | wc -l | tr -d ' ')"
    if [ "$n" != "$shared_skills" ]; then
        echo "  - dist/$engine: SKILL.md count $n != shared $shared_skills" >&2
        errors=$((errors + 1))
    fi

    if [ "$engine" = claude ]; then manifest="$out/.claude-plugin/plugin.json"; else manifest="$out/.codex-plugin/plugin.json"; fi
    if [ ! -f "$manifest" ]; then
        echo "  - dist/$engine: missing plugin.json" >&2
        errors=$((errors + 1))
    elif ! grep -q '"version"' "$manifest"; then
        echo "  - dist/$engine: plugin.json has no version" >&2
        errors=$((errors + 1))
    fi

    if [ ! -f "$out/hooks/hooks.json" ]; then
        echo "  - dist/$engine: missing hooks/hooks.json" >&2
        errors=$((errors + 1))
    fi
done

# Codex subagents must carry the three required TOML fields
for toml in "$DIST"/codex/.codex/agents/*.toml; do
    [ -f "$toml" ] || continue
    for field in name description developer_instructions; do
        if ! grep -Eq "^[[:space:]]*$field[[:space:]]*=" "$toml"; then
            echo "  - $(basename "$toml"): missing required field '$field'" >&2
            errors=$((errors + 1))
        fi
    done
done

if [ "$errors" -gt 0 ]; then
    echo "VALIDATION FAILED ($errors)" >&2
    exit 1
fi

echo "OK — $shared_skills skills in each engine; manifests valid."
