#!/usr/bin/env pwsh
# Assemble self-contained, IDE-droppable plugin folders under dist/<engine>.
#
# Source of truth:
#   shared/{skills,hooks,templates}   engine-agnostic, copied into BOTH engines
#   engines/claude/*                  Claude-specific (.claude-plugin, agents, commands)
#   engines/codex/*                   Codex-specific (.codex-plugin, agents, prompts, AGENTS.md)
#
# Output (committed, this is what the IDE downloads):
#   dist/claude/   drop into <project>/.claude/  (or install as a Claude plugin)
#   dist/codex/    drop into <project>/           (.codex/agents, AGENTS.md, skills, hooks)
#
# Usage:  pwsh scripts/build.ps1

$ErrorActionPreference = 'Stop'
$root   = Split-Path -Parent $PSScriptRoot
$shared = Join-Path $root 'shared'
$dist   = Join-Path $root 'dist'

$engines = @('claude', 'codex')

function Copy-Into($srcDir, $dstDir) {
    Copy-Item -Path (Join-Path $srcDir '*') -Destination $dstDir -Recurse -Force
}

# ---- assemble ----------------------------------------------------------------
foreach ($engine in $engines) {
    $src = Join-Path $root "engines\$engine"
    $out = Join-Path $dist $engine

    if (Test-Path $out) { Remove-Item -Recurse -Force $out }
    New-Item -ItemType Directory -Force -Path $out | Out-Null

    # engine-specific files (includes dot-prefixed manifest dir)
    Copy-Into $src $out

    # shared, engine-agnostic payload
    foreach ($s in @('skills', 'hooks', 'templates')) {
        Copy-Item -Path (Join-Path $shared $s) -Destination $out -Recurse -Force
    }

    Write-Host "built dist/$engine" -ForegroundColor Green
}

# ---- per-engine drop README --------------------------------------------------
$claudeReadme = @'
# kensa-qa -- Claude Code engine (built artifact)

This folder is generated by `scripts/build.ps1` -- do not edit by hand. Edit the
sources under `shared/` and `engines/claude/`, then rebuild.

## What this is
A complete, self-contained Claude Code plugin. `.claude-plugin/plugin.json` wires
the Stop hooks and the bundled sequential-thinking MCP; everything else loads by
convention.

```
dist/claude/
  .claude-plugin/plugin.json   # hooks + bundled sequential-thinking MCP
  agents/        # test-lead-agent, qa-engineer-agent, strategist
  commands/      # 12 slash commands (/new-feature, /audit, ...)
  skills/        # 31 ISTQB-grounded + tooling skills
  hooks/         # Stop hooks: memory checkpoint + debug log
  templates/     # .tms/memory scaffolding used by /setup
```

## How the IDE installs this
Drop this folder into the project as a project-scoped plugin (e.g.
`<project>/.claude/plugins/kensa-qa/`) and enable it. Then run `/setup` in the
project to bootstrap `.tms/memory/` and wire SOT MCP servers.
'@

$codexReadme = @'
# kensa-qa -- Codex engine (built artifact)

This folder is generated by `scripts/build.ps1` -- do not edit by hand. Edit the
sources under `shared/` and `engines/codex/`, then rebuild.

## How the IDE installs this
Copy the contents of this folder into the target project root -- the layout already
mirrors where Codex expects each piece:

```
<project>/
  .codex/
    agents/*.toml            # test-lead-agent, qa-engineer-agent, strategist (project-scoped subagents)
    prompts/*.md             # 12 custom prompts (/kensa-new-feature, ...)
  .codex-plugin/plugin.json  # skills + hooks manifest (for `codex plugin` install)
  AGENTS.md                  # Codex operating manual (merge into project AGENTS.md)
  skills/                    # 31 ISTQB-grounded + tooling skills
  hooks/                     # Stop hooks: memory checkpoint + debug log
  templates/                 # .tms/memory scaffolding used by /kensa-setup
```

Codex loads `.codex/agents/*.toml` as project-scoped subagents and concatenates
`AGENTS.md` into its instructions automatically. Run `/kensa-setup` to bootstrap memory.
'@

Set-Content -Path (Join-Path $dist 'claude\README.md') -Value $claudeReadme -Encoding utf8
Set-Content -Path (Join-Path $dist 'codex\README.md')  -Value $codexReadme  -Encoding utf8

# ---- validation --------------------------------------------------------------
$errors = @()
$sharedSkillCount = (Get-ChildItem -Recurse (Join-Path $shared 'skills') -Filter 'SKILL.md').Count

foreach ($engine in $engines) {
    $out = Join-Path $dist $engine

    # skills materialized 1:1
    $n = (Get-ChildItem -Recurse (Join-Path $out 'skills') -Filter 'SKILL.md').Count
    if ($n -ne $sharedSkillCount) {
        $errors += "dist/${engine}: SKILL.md count $n != shared $sharedSkillCount"
    }

    # manifest parses + version present
    $manifestDir = if ($engine -eq 'claude') { '.claude-plugin' } else { '.codex-plugin' }
    $manifest = Join-Path $out "$manifestDir\plugin.json"
    if (-not (Test-Path $manifest)) {
        $errors += "dist/${engine}: missing $manifestDir/plugin.json"
    } else {
        try {
            $m = Get-Content $manifest -Raw | ConvertFrom-Json
            if (-not $m.version) { $errors += "dist/${engine}: plugin.json has no version" }
        } catch { $errors += "dist/${engine}: plugin.json invalid JSON: $_" }
    }

    # hooks manifest present
    if (-not (Test-Path (Join-Path $out 'hooks\hooks.json'))) {
        $errors += "dist/${engine}: missing hooks/hooks.json"
    }
}

# Codex subagents must carry the three required TOML fields
foreach ($toml in Get-ChildItem -Recurse (Join-Path $dist 'codex\.codex') -Filter '*.toml' -ErrorAction SilentlyContinue) {
    $body = Get-Content $toml.FullName -Raw
    foreach ($field in @('name', 'description', 'developer_instructions')) {
        if ($body -notmatch "(?m)^\s*$field\s*=") {
            $errors += "$($toml.Name): missing required field '$field'"
        }
    }
}

if ($errors.Count -gt 0) {
    Write-Host "`nVALIDATION FAILED:" -ForegroundColor Red
    $errors | ForEach-Object { Write-Host "  - $_" -ForegroundColor Red }
    exit 1
}

Write-Host "`nOK -- $sharedSkillCount skills in each engine; manifests valid." -ForegroundColor Green
