#!/usr/bin/env bash
# Assemble self-contained, IDE-droppable plugin folders under dist/<engine>,
# split into an always-installed BASE and optional, additive BUNDLES.
# POSIX/bash mirror of build.ps1 — see that file for the full rationale.
#
# Requires jq (reads catalog.json). Usage:  sh scripts/build.sh

set -eu

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SHARED="$ROOT/shared"
DIST="$ROOT/dist"
CATALOG="$ROOT/catalog.json"
ENGINES="claude codex"

command -v jq >/dev/null 2>&1 || { echo "build.sh requires 'jq' (parses catalog.json). Install jq or run scripts/build.ps1." >&2; exit 1; }

# ---- helpers -----------------------------------------------------------------
copy_skill() {  # name destSkillsDir
    src="$SHARED/skills/$1"
    [ -d "$src" ] || { echo "skill not found: shared/skills/$1" >&2; exit 1; }
    mkdir -p "$2"; cp -R "$src" "$2/"
}

copy_engine_agent() {  # engine name dstRoot
    if [ "$1" = claude ]; then src="$ROOT/engines/claude/agents/$2.md"; dst="$3/agents"
    else src="$ROOT/engines/codex/.codex/agents/$2.toml"; dst="$3/.codex/agents"; fi
    [ -f "$src" ] || { echo "agent not found for $1: $2" >&2; exit 1; }
    mkdir -p "$dst"; cp "$src" "$dst/"
}

copy_engine_command() {  # engine name dstRoot
    if [ "$1" = claude ]; then src="$ROOT/engines/claude/commands/$2.md"; dst="$3/commands"
    else src="$ROOT/engines/codex/.codex/prompts/kensa-$2.md"; dst="$3/.codex/prompts"; fi
    [ -f "$src" ] || { echo "command not found for $1: $2" >&2; exit 1; }
    mkdir -p "$dst"; cp "$src" "$dst/"
}

cat_base()   { jq -r ".base.$1[]?" "$CATALOG"; }                                       # $1 = skills|agents|commands
bundle_ids() { jq -r '.bundles[].id' "$CATALOG"; }
bundle_arr() { jq -r --arg id "$1" ".bundles[]|select(.id==\$id)|.$2[]?" "$CATALOG"; } # $1 = id, $2 = skills|agents|commands

# ---- assemble ----------------------------------------------------------------
for engine in $ENGINES; do
    engOut="$DIST/$engine"
    rm -rf "$engOut"; mkdir -p "$engOut"
    base="$engOut/base"; mkdir -p "$base"

    # 1) engine-specific base files, EXCLUDING membership-filtered dirs
    src="$ROOT/engines/$engine"
    if [ "$engine" = claude ]; then exclude="agents commands"; else exclude=".codex"; fi
    for item in "$src"/* "$src"/.*; do
        name="$(basename "$item")"
        case "$name" in .|..) continue ;; esac
        skip=0; for ex in $exclude; do [ "$name" = "$ex" ] && skip=1; done
        [ "$skip" -eq 1 ] && continue
        cp -R "$item" "$base/"
    done

    # 2) base agents + commands (membership-filtered)
    for a in $(cat_base agents);   do copy_engine_agent   "$engine" "$a" "$base"; done
    for c in $(cat_base commands); do copy_engine_command "$engine" "$c" "$base"; done

    # 3) base shared payload
    for s in $(cat_base skills); do copy_skill "$s" "$base/skills"; done
    for p in hooks templates; do cp -R "$SHARED/$p" "$base/"; done
    # Claude registers the Stop hook inline in plugin.json; hooks.json is Codex-only
    # (shipping it for Claude double-fires the Stop hook).
    [ "$engine" = claude ] && rm -f "$base/hooks/hooks.json"

    # 4) bundles
    for id in $(bundle_ids); do
        bOut="$engOut/bundles/$id"; mkdir -p "$bOut"
        for s in $(bundle_arr "$id" skills);   do copy_skill "$s" "$bOut/skills"; done
        for a in $(bundle_arr "$id" agents);   do copy_engine_agent   "$engine" "$a" "$bOut"; done
        for c in $(bundle_arr "$id" commands); do copy_engine_command "$engine" "$c" "$bOut"; done
    done

    echo "built dist/$engine"
done

# ---- per-engine drop README --------------------------------------------------
cat > "$DIST/claude/README.md" <<'EOF'
# kensa-qa — Claude Code engine (built artifact)

Generated by `scripts/build.sh` — do not edit by hand. Edit `catalog.json`,
`shared/`, and `engines/claude/`, then rebuild. `base/` is always installed;
`bundles/<id>/` are optional add-ons merged in on selection.
EOF
cat > "$DIST/codex/README.md" <<'EOF'
# kensa-qa — Codex engine (built artifact)

Generated by `scripts/build.sh` — do not edit by hand. Edit `catalog.json`,
`shared/`, and `engines/codex/`, then rebuild. `base/` is always installed;
`bundles/<id>/` are optional add-ons merged into the project root on selection.
EOF

# ---- validation --------------------------------------------------------------
errors=0
shared_skills="$(find "$SHARED/skills" -name SKILL.md | wc -l | tr -d ' ')"

# catalog covers every shared skill exactly once
cat_skills="$(jq -r '[.base.skills[], (.bundles[].skills // [])[]] | .[]' "$CATALOG")"
cat_count="$(printf '%s\n' "$cat_skills" | sed '/^$/d' | wc -l | tr -d ' ')"
dupes="$(printf '%s\n' "$cat_skills" | sed '/^$/d' | sort | uniq -d)"
[ -n "$dupes" ] && { echo "  - catalog.json: skill(s) in more than one place: $(echo $dupes)" >&2; errors=$((errors+1)); }
[ "$cat_count" != "$shared_skills" ] && { echo "  - catalog.json maps $cat_count skills but shared has $shared_skills" >&2; errors=$((errors+1)); }

for engine in $ENGINES; do
    engOut="$DIST/$engine"; base="$engOut/base"

    n="$(find "$engOut" -name SKILL.md | wc -l | tr -d ' ')"
    [ "$n" != "$shared_skills" ] && { echo "  - dist/$engine: SKILL.md count $n != shared $shared_skills" >&2; errors=$((errors+1)); }

    if [ "$engine" = claude ]; then manifest="$base/.claude-plugin/plugin.json"; else manifest="$base/.codex-plugin/plugin.json"; fi
    if [ ! -f "$manifest" ]; then
        echo "  - dist/$engine/base: missing plugin.json" >&2; errors=$((errors+1))
    elif ! grep -q '"version"' "$manifest"; then
        echo "  - dist/$engine/base: plugin.json has no version" >&2; errors=$((errors+1))
    fi

    for script in save-memory-stop.js save-memory-stop.sh save-memory-stop.ps1; do
        [ ! -f "$base/hooks/$script" ] && { echo "  - dist/$engine/base: missing hooks/$script" >&2; errors=$((errors+1)); }
    done
    if [ "$engine" = codex ]; then
        [ ! -f "$base/hooks/hooks.json" ] && { echo "  - dist/$engine/base: missing hooks/hooks.json" >&2; errors=$((errors+1)); }
    else
        [ -f "$base/hooks/hooks.json" ] && { echo "  - dist/$engine/base: stray hooks/hooks.json (would double-fire)" >&2; errors=$((errors+1)); }
        grep -q '"Stop"' "$manifest" || { echo "  - dist/$engine/base: plugin.json missing Stop hook" >&2; errors=$((errors+1)); }
    fi

    # every catalog bundle produced a dir
    for id in $(bundle_ids); do
        [ -d "$engOut/bundles/$id" ] || { echo "  - dist/$engine: bundle '$id' produced no directory" >&2; errors=$((errors+1)); }
    done
done

# Codex subagents (base + bundles) must carry the three required TOML fields
for toml in $(find "$DIST/codex" -name '*.toml'); do
    for field in name description developer_instructions; do
        grep -Eq "^[[:space:]]*$field[[:space:]]*=" "$toml" || { echo "  - $(basename "$toml"): missing required field '$field'" >&2; errors=$((errors+1)); }
    done
done

if [ "$errors" -gt 0 ]; then
    echo "VALIDATION FAILED ($errors)" >&2
    exit 1
fi

echo "OK — $shared_skills skills across base+bundles in each engine; manifests valid."
